DATASEG SEGMENT
    ;此处输入数据段代码  
    ;D1 DB 100 DUP(?)
    I DB ?
DATASEG ENDS


STACKSEG SEGMENT
    ;此处输入堆栈段代码
STACKSEG ENDS


CODESEG SEGMENT
    ASSUME CS:CODESEG,DS:DATASEG,SS:STACKSEG
START:
    MOV AX,DATASEG
    MOV DS,AX
    MOV CX,100
    MOV AX,0
A: ADD AX,CX
    LOOP A
    PUSH AX
    MOV CX,10
    MOV BX,10000
B: XOR DX,DX
    MOV AX,BX
    DIV CX
    CMP AX,0
    JL SUM
    JE SUM
    MOV BX,AX
    XOR DX,DX
    POP AX
    DIV BX
    PUSH DX
    ADD AL,30H
    MOV DL,AL
    MOV AH,2
    INT 21H
    JMP B
SUM:    
    MOV AH,4CH
    INT 21H
CODESEG ENDS
    END START